//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec Test


namespace Test

open JsonPlugin

type Serializer =
    static member inline public Serialize(str : string) = Types.JsonValue.String(str)
    static member inline public Serialize(number : int16) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : int32) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : int64) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : uint16) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : uint32) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : uint64) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : float) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : float32) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : byte) = Types.JsonValue.Number(decimal (number))
    static member inline public Serialize(number : sbyte) = Types.JsonValue.Number(decimal (number))

    static member inline public Serialize(theObject : Model.SomeRecord) =
        Types.JsonValue.Record([| "foo", Serializer.Serialize(theObject.foo)
                                  "bar", Serializer.Serialize(theObject.bar)
                                  "spam", Serializer.Serialize(theObject.spam) |])

    static member inline public Serialize(theObject : Model.SomeRecord2) =
        Types.JsonValue.Record([| "foo", Serializer.Serialize(theObject.foo) |])
    static member inline public Serialize(theObject : Model.SomeRecord3) =
        Types.JsonValue.Record([| "foo", Serializer.Serialize(theObject.foo)
                                  "bar", Serializer.Serialize(theObject.bar) |])
